name: Build Luanti for Raspberry Pi 5 (QEMU Emulation)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 120  # Увеличиваем таймаут для эмуляции

    steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
      with:
        platforms: arm64

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Checkout Luanti source
      uses: actions/checkout@v4
      with:
        path: luanti

    - name: Build in ARM64 environment
      run: |
        # Создаем Dockerfile для сборки
        cat > Dockerfile <<EOF
        FROM arm64v8/ubuntu:22.04

        # Установка зависимостей
        RUN apt-get update && apt-get install -y \\
            build-essential \\
            cmake \\
            git \\
            ninja-build \\
            libx11-dev \\
            libxxf86vm-dev \\
            libgl1-mesa-dev \\
            libglu1-mesa-dev \\
            libopenal-dev \\
            libvorbis-dev \\
            libogg-dev \\
            libfreetype6-dev \\
            libsqlite3-dev \\
            libcurl4-openssl-dev \\
            libjpeg-dev \\
            libpng-dev \\
            zlib1g-dev \\
            liblua5.1-0-dev \\
            libgmp-dev \\
            libjson-c-dev \\
            libzstd-dev \\
            libssl-dev \\
            libsdl2-dev

        # Копируем исходники Luanti
        COPY luanti /luanti

        WORKDIR /luanti

        # Конфигурация и сборка
        RUN cmake . -B build \\
            -DENABLE_GETTEXT=OFF \\
            -DENABLE_LUAJIT=ON \\
            -DENABLE_SOUND=ON \\
            -DENABLE_CURL=ON \\
            -DENABLE_FREETYPE=ON \\
            -DBUILD_SERVER=OFF \\
            -DBUILD_CLIENT=ON \\
            -DVERSION_EXTRA=RPI5-QEMU \\
            -DCMAKE_BUILD_TYPE=Release

        RUN cmake --build build -j\$(nproc) --target install
        EOF

        # Собираем образ и извлекаем бинарник
        docker buildx build --platform linux/arm64 -t luanti-builder --output type=local,dest=./output .

    - name: Verify executable
      run: |
        file output/luanti/install/bin/luanti
        echo "Dynamic dependencies:"
        readelf -d output/luanti/install/bin/luanti | grep NEEDED

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: luanti-rpi5
        path: output/luanti/install/bin/luanti
