name: Build Luanti for Raspberry Pi 5 (Static)

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: debian:bullseye

    env:
      DEPS_INSTALL_DIR: ${{ github.workspace }}/deps/install
      TOOLCHAIN_FILE: ${{ github.workspace }}/toolchains/aarch64-linux-gnu.cmake

    steps:
    - name: Install build dependencies
      run: |
        apt-get update
        apt-get install -y --no-install-recommends \
          ca-certificates \
          g++-aarch64-linux-gnu \
          cmake \
          git \
          wget \
          build-essential \
          libx11-dev \
          libxxf86vm-dev \
          libgl1-mesa-dev \
          libglu1-mesa-dev \
          pkg-config \
          ninja-build  # Required for OpenAL-Soft build

    - name: Checkout Luanti source
      uses: actions/checkout@v3
      with:
        path: luanti

    - name: Create toolchain file
      run: |
        mkdir -p toolchains
        cat > toolchains/aarch64-linux-gnu.cmake <<'EOF'
        set(CMAKE_SYSTEM_NAME Linux)
        set(CMAKE_SYSTEM_PROCESSOR aarch64)
        
        set(CMAKE_C_COMPILER aarch64-linux-gnu-gcc)
        set(CMAKE_CXX_COMPILER aarch64-linux-gnu-g++)
        
        set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
        set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
        set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
        set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
        
        set(CMAKE_C_FLAGS "-static")
        set(CMAKE_CXX_FLAGS "-static")
        EOF

    - name: Create directories for dependencies
      run: |
        mkdir -p deps/build deps/install

    # ... (other dependency build steps remain the same) ...

    - name: Build OpenAL-Soft (Fixed)
      run: |
        cd deps
        git clone --depth 1 https://github.com/kcat/openal-soft.git
        mkdir -p openal-soft/build
        cd openal-soft/build
        cmake .. \
          -DCMAKE_TOOLCHAIN_FILE=$TOOLCHAIN_FILE \
          -DCMAKE_INSTALL_PREFIX=$DEPS_INSTALL_DIR \
          -DCMAKE_FIND_ROOT_PATH=$DEPS_INSTALL_DIR \
          -DLIBTYPE=STATIC \
          -DALSOFT_EXAMPLES=OFF \
          -DALSOFT_UTILS=OFF \
          -DALSOFT_NO_CONFIG_UTIL=ON \
          -G Ninja
        cmake --build . --target install

    - name: Build IrrlichtMt (Fixed)
      run: |
        cd deps
        git clone --depth 1 --branch mt https://github.com/minetest/irrlicht.git
        cd irrlicht
        mkdir build && cd build
        cmake .. \
          -DCMAKE_TOOLCHAIN_FILE=$TOOLCHAIN_FILE \
          -DCMAKE_INSTALL_PREFIX=$DEPS_INSTALL_DIR \
          -DCMAKE_FIND_ROOT_PATH=$DEPS_INSTALL_DIR \
          -DBUILD_SHARED_LIBS=OFF \
          -DIRRLICHT_BUILD_STATIC=ON
        make install

    - name: Build Luanti
      run: |
        cd luanti
        cmake . -B build \
          -DCMAKE_TOOLCHAIN_FILE=$TOOLCHAIN_FILE \
          -DCMAKE_FIND_ROOT_PATH=$DEPS_INSTALL_DIR \
          -DENABLE_GETTEXT=OFF \
          -DENABLE_LUAJIT=ON \
          -DENABLE_SOUND=ON \
          -DENABLE_CURL=ON \
          -DENABLE_FREETYPE=ON \
          -DBUILD_SERVER=OFF \
          -DBUILD_CLIENT=ON \
          -DVERSION_EXTRA=RPI5-STATIC \
          -DCMAKE_PREFIX_PATH=$DEPS_INSTALL_DIR \
          -DCMAKE_EXE_LINKER_FLAGS="-static -static-libgcc -static-libstdc++" \
          -DCMAKE_INSTALL_PREFIX=./install
        cmake --build build -j$(nproc) --target install

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: luanti-rpi5-static
        path: luanti/install/bin/luanti
