name: Build Luanti Static Binary for Raspberry Pi 5

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Install cross toolchain and dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc-aarch64-linux-gnu g++-aarch64-linux-gnu cmake ninja-build

    - name: Configure CMake for static build
      run: |
        mkdir -p build
        cd build
        cmake .. -G Ninja \
          -DCMAKE_SYSTEM_NAME=Linux \
          -DCMAKE_SYSTEM_PROCESSOR=aarch64 \
          -DCMAKE_C_COMPILER=aarch64-linux-gnu-gcc \
          -DCMAKE_CXX_COMPILER=aarch64-linux-gnu-g++ \
          -DBUILD_CLIENT=0 \
          -DBUILD_SERVER=1 \
          -DRUN_IN_PLACE=1 \
          -DBUILD_UNITTESTS=0 \
          -DLUA_INCLUDE_DIR=../luajit/src/ \
          -DLUA_LIBRARY=../luajit/src/libluajit.a \
          -DCMAKE_EXE_LINKER_FLAGS="-static" 

    - name: Build Luanti server statically
      run: |
        cd build
        ninja

    - name: Upload static executable artifact
      uses: actions/upload-artifact@v4
      with:
        name: luanti-server-static
        path: build/bin/luantiserver
