name: Build Luanti for Raspberry Pi 5

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  build-luanti-rpi5:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up QEMU for aarch64 emulation
        uses: docker/setup-qemu-action@v2
        with:
          platforms: linux/arm64

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Luanti for aarch64
        run: |
          # Создаем временную директорию для сборки
          mkdir -p build-luanti

          # Клонируем Luanti, если не из репозитория в checkout
          # git clone --depth 1 https://github.com/luanti/luanti.git build-luanti

          # Переходим в папку сборки
          cd build-luanti

          # Создаем build директорию
          mkdir -p build && cd build

          # Запускаем cmake с указанием целевой платформы и установкой
          cmake .. -DCMAKE_BUILD_TYPE=Release

          # Компилируем с использованием всех доступных ядер
          make -j$(nproc)

          # Копируем скомпилированный бинарник в корневую папку
          cp ./bin/luanti $GITHUB_WORKSPACE/luanti-rpi5-binary

      - name: Upload Luanti binary artifact
        uses: actions/upload-artifact@v4
        with:
          name: luanti-rpi5-binary
          path: luanti-rpi5-binary
