name: Build Luanti for Raspberry Pi 5

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-luanti-rpi5:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up QEMU for aarch64 emulation
        uses: docker/setup-qemu-action@v2
        with:
          platforms: linux/arm64

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            cmake \
            libsdl2-dev \
            libglew-dev \
            libssl-dev \
            libogg-dev \
            libvorbis-dev \
            libcurl4-openssl-dev \
            zlib1g-dev \
            libjpeg-dev \
            libpng-dev

      - name: Build Luanti for aarch64
        run: |
          mkdir -p build
          cd build
          cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_SYSTEM_NAME=Linux -DCMAKE_SYSTEM_PROCESSOR=aarch64
          make -j$(nproc)
          cp ./bin/luanti $GITHUB_WORKSPACE/luanti-rpi5-binary

      - name: Upload Luanti binary artifact
        uses: actions/upload-artifact@v4
        with:
          name: luanti-rpi5-binary
          path: luanti-rpi5-binary
