name: Build Luanti for aarch64

on:
  workflow_dispatch: # Allows manual triggering from the GitHub Actions tab

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v2

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub (optional, if pushing images)
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Luanti for aarch64
        run: |
          docker buildx build --platform linux/arm64 -t luanti-aarch64:latest --load .

      # Если нужно сохранить бинарный артефакт, добавьте шаг для копирования сборки из контейнера или сборку на runner и сохранение артефакта

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: luanti-aarch64-binaries
          path: ./path/to/build/output
